### ISSUE TITLE
game crashes on initialising part 2

### ISSUE THREAD

**Issue by kira1000** [ProsperCraft/drtardis2#1]
Hi, for some reason the mudpack crashes during the 2nd phase of mod initialisation, more specifically during Aether2's initialisation.  here's the log file:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2019-07-02 15:20:03 AEST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Aether II (aether)
Caused by: java.lang.NoClassDefFoundError: com/gildedgames/aether/client/renderer/items/WrappingPaperColorHandler
    at com.gildedgames.aether.client.renderer.AetherRenderers.init(AetherRenderers.java:46)
    at com.gildedgames.aether.client.ClientProxy$$Lambda$3425/1820595963.run(Unknown Source)
    at com.gildedgames.aether.common.util.helpers.PerfHelper.measure(PerfHelper.java:11)
    at com.gildedgames.aether.client.ClientProxy.init(ClientProxy.java:98)
    at com.gildedgames.aether.common.AetherCore.onModInit(AetherCore.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.gildedgames.aether.client.renderer.items.WrappingPaperColorHandler
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 45 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.HashMap$EntrySet.iterator(HashMap.java:1005)
    at java.util.HashMap.putMapEntries(HashMap.java:511)
    at java.util.HashMap.<init>(HashMap.java:489)
    at java.util.jar.Attributes.<init>(Attributes.java:84)
    at java.util.jar.Attributes.clone(Attributes.java:291)
    at sun.net.www.protocol.jar.URLJarFile.getManifest(URLJarFile.java:155)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:147)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.gildedgames.aether.client.renderer.AetherRenderers.init(AetherRenderers.java:46)
    at com.gildedgames.aether.client.ClientProxy$$Lambda$3425/1820595963.run(Unknown Source)
    at com.gildedgames.aether.common.util.helpers.PerfHelper.measure(PerfHelper.java:11)
    at com.gildedgames.aether.client.ClientProxy.init(ClientProxy.java:98)
    at com.gildedgames.aether.common.AetherCore.onModInit(AetherCore.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 596491008 bytes (568 MB) / 4772593664 bytes (4551 MB) up to 4772593664 bytes (4551 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 114 mods loaded, 114 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                        | Version              | Source                                            | Signature                                |
       |:----- |:------------------------- |:-------------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft                 | 1.12.2               | minecraft.jar                                     | None                                     |
       | LCHI  | mcp                       | 9.42                 | minecraft.jar                                     | None                                     |
       | LCHI  | sampler                   | 1.84                 | sampler-1.84.jar                                  | None                                     |
       | LCHI  | FML                       | 8.0.99.99            | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge                     | 14.23.5.2838         | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | creativecoredummy         | 1.0.0                | minecraft.jar                                     | None                                     |
       | LCHI  | littletilescore           | 1.0.0                | minecraft.jar                                     | None                                     |
       | LCHI  | OpenEye                   | 0.8                  | OpenEye-1.12.2-0.8.jar                            | None                                     |
       | LCHI  | moresoundconfigcore       | 1.0.0                | minecraft.jar                                     | None                                     |
       | LCHI  | randompatches             | 1.12.2-1.16.3.1      | randompatches-1.12.2-1.16.3.1.jar                 | None                                     |
       | LCHI  | ctm                       | MC1.12.2-0.3.3.22    | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
       | LCHI  | appliedenergistics2       | rv6-stable-6         | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHI  | bdlib                     | 1.14.3.12            | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
       | LCHI  | ae2stuff                  | 0.7.0.4              | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
       | LCHI  | orbis-lib                 | 0.2.0                | orbis-lib-1.12.2-0.2.0+build79.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHE  | aether                    | 0.2.2                | aether_ii-1.12.2-0.2.2+build79-universal.jar      | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCH   | mdxlib                    | 3.0.0.15             | mdxlib-3.0.0.15.jar                               | None                                     |
       | LCH   | avp                       | 6.0.0.34             | aliensvspredator-6.0.0.34.jar                     | None                                     |
       | LCH   | aoa3                      | 3.1.2.b              | AoA3-3.1.2.b.jar                                  | None                                     |
       | LCH   | jei                       | 4.15.0.283           | jei_1.12.2-4.15.0.283.jar                         | None                                     |
       | LCH   | appleskin                 | 1.0.9                | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | LCH   | architecturecraft         | @VERSION@            | architecturecraft-1.12-3.80.jar                   | None                                     |
       | LCH   | atum                      | 2.0.10               | Atum-1.12.2-2.0.10.jar                            | None                                     |
       | LCH   | badwithernocookiereloaded | 1.12.2-3.3.16        | badwithernocookiereloaded-1.12.2-3.3.16.jar       | None                                     |
       | LCH   | betterbuilderswands       | 0.13.2               | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
       | LCH   | bettermagnets             | 0.1                  | bettermagnets-mc1.12.x-v1.11.jar                  | None                                     |
       | LCH   | betterquesting            | 3.5.300              | BetterQuesting-3.5.300.jar                        | None                                     |
       | LCH   | bibliocraft               | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
       | LCH   | blockmasher               | 1.0                  | BlockMasher_V1.1.jar                              | None                                     |
       | LCH   | buildinggadgets           | 2.6.8                | BuildingGadgets-2.6.8.jar                         | None                                     |
       | LCH   | chameleon                 | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                          | None                                     |
       | LCH   | chisel                    | MC1.12.2-0.2.1.35    | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
       | LCH   | chunkpregenerator         | 2.1                  | Chunk Pregenerator V1.12-2.1.jar                  | None                                     |
       | LCH   | clockworkphase            | 1.0g                 | ClockworkPhase-1.12.2-1.0g.jar                    | None                                     |
       | LCH   | codechickenlib            | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | fp                        | 26.4.82              | Futurepack-1.12.2-26.4.82.jar                     | a8cfb0576c44b2711002b9e45850732f0b8c7cb6 |
       | LCH   | crafttweaker              | 4.1.19               | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCH   | cookingforblockheads      | 6.4.70               | CookingForBlockheads_1.12.2-6.4.70.jar            | None                                     |
       | LCH   | ctgui                     | 1.0.0                | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCH   | crafttweakerjei           | 2.0.3                | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCH   | creativecore              | 1.9.9                | CreativeCore_v1.9.45_mc1.12.2.jar                 | None                                     |
       | LCH   | culinaryconstruct         | 1.3.3                | culinaryconstruct-1.3.3.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | custommainmenu            | 2.0.9                | CustomMainMenu-MC1.12.2-2.0.9.jar                 | None                                     |
       | LCH   | dawnoftime                | 0.1                  | dawnoftime-alpha-1.0.2.jar                        | None                                     |
       | LCH   | ptrmodellib               | 1.0.4                | PTRLib-1.0.4.jar                                  | None                                     |
       | LCH   | props                     | 2.6.2                | Decocraft-2.6.2_1.12.2.jar                        | None                                     |
       | LCH   | journeymap                | 1.12.2-5.5.5b7       | journeymap-1.12.2-5.5.5b7.jar                     | None                                     |
       | LCH   | defaultoptions            | 9.2.8                | DefaultOptions_1.12.2-9.2.8.jar                   | None                                     |
       | LCH   | demagnetize               | 1.12.2-1.0.1         | demagnetize-1.12.2-1.0.1.jar                      | None                                     |
       | LCH   | eleccore                  | 1.9.452              | ElecCore-1.12.2-1.9.452.jar                       | None                                     |
       | LCH   | elevatorid                | 1.4.2                | ElevatorMod-1.12.2-1.4.2.jar                      | None                                     |
       | LCH   | csb_ench_table            | 1.1.3                | EnchantingTable-1.12-1.1.3.jar                    | None                                     |
       | LCH   | shetiphiancore            | 3.5.9                | shetiphiancore-1.12.0-3.5.9.jar                   | None                                     |
       | LCH   | endertanks                | 1.6.8                | endertanks-1.12.0-1.6.8.jar                       | None                                     |
       | LCH   | engineersdecor            | 1.0.9-b2             | engineersdecor-1.12.2-1.0.9-b2.jar                | ed58ed655893ced6280650866985abcae2bf7559 |
       | LCH   | erebus                    | 1.0.30               | Erebus-1.0.30.jar                                 | None                                     |
       | LCH   | fastleafdecay             | v14                  | FastLeafDecay-v14.jar                             | None                                     |
       | LCH   | fp.api                    | 1.1.0                | Futurepack-1.12.2-26.4.82.jar                     | None                                     |
       | LCH   | gaiadimension             | 1.0.5                | gaiadimension-1.12.2-1.0.5.jar                    | None                                     |
       | LCH   | glacidus                  | 1.2.1                | Glacidus-1.12.2-v1.2.1.jar                        | None                                     |
       | LCH   | gregtech                  | 1.8.4.419            | gregtech-1.12.2-1.8.4.419.jar                     | None                                     |
       | LCH   | railcraft                 | 12.0.0               | railcraft-12.0.0.jar                              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCH   | theoneprobe               | 1.4.28               | theoneprobe-1.12-1.4.28.jar                       | None                                     |
       | LCH   | twilightforest            | 3.9.888              | twilightforest-1.12.2-3.9.888-universal.jar       | None                                     |
       | LCH   | immersiveengineering      | 0.12-89              | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCH   | immersivepetroleum        | 1.1.9                | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
       | LCH   | inventorytweaks           | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | ironbackpacks             | 1.12.2-3.0.8-12      | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
       | LCH   | keywizard                 | 1.12.2-1.7           | keywizard-1.12.2-1.7.jar                          | None                                     |
       | LCH   | labyrinth                 | ${version}           | Labyrinth-1.12.2-1.0.jar                          | None                                     |
       | LCH   | landlust                  | 1.12.2-0.3.6         | landlust-1.12.2-0.3.6.jar                         | None                                     |
       | LCH   | littletiles               | 1.5.0                | LittleTiles_v1.5.0-pre135_mc1.12.2.jar            | None                                     |
       | LCH   | lostcities                | 2.0.20               | lostcities-1.12-2.0.20.jar                        | None                                     |
       | LCH   | lostsouls                 | 1.1.4                | lostsouls-1.12-1.1.4.jar                          | None                                     |
       | LCH   | mcjtylib_ng               | 3.5.3                | mcjtylib-1.12-3.5.3.jar                           | None                                     |
       | LCH   | testdummy                 | 1.12                 | MmmMmmMmmMmm-1.12-1.14.jar                        | None                                     |
       | LCH   | modnametooltip            | 1.10.0               | modnametooltip_1.12.2-1.10.0.jar                  | None                                     |
       | LCH   | numina                    | 1.12.2-1.0.38        | Numina-1.12.2-1.0.38.jar                          | None                                     |
       | LCH   | powersuits                | 1.12.2-1.0.44        | ModularPowersuits-1.12.2-1.0.44.jar               | None                                     |
       | LCH   | moolands                  | 1.12.2-1.1.5         | moolands-1.12.2-1.1.5.jar                         | None                                     |
       | LCH   | moreoverlays              | 1.14                 | moreoverlays-1.14-mc1.12.2.jar                    | None                                     |
       | LCH   | morpheus                  | 1.12.2-3.5.106       | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
       | LCH   | mousetweaks               | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
       | LCH   | multibeds                 | 1.4.4                | multibeds-1.12.0-1.4.4.jar                        | None                                     |
       | LCH   | multistorage              | 1.4.14               | multistorage-1.12.0-1.4.14.jar                    | None                                     |
       | LCH   | nonausea                  | 1.0                  | NoNausea-MC1.12-1.0.jar                           | None                                     |
       | LCH   | norecipebook              | 1.2.1                | noRecipeBook_v1.2.2formc1.12.2.jar                | None                                     |
       | LCH   | neid                      | 1.5.4.4              | NotEnoughIDs-1.5.4.4.jar                          | None                                     |
       | LCH   | patchouli                 | 1.0-20               | Patchouli-1.0-20.jar                              | None                                     |
       | LCH   | placebo                   | 1.6.0                | Placebo-1.12.2-1.6.0.jar                          | None                                     |
       | LCH   | questbook                 | 3.1.EXP_NET2-1.12    | questbook-3.1.EXP_NET2-1.12.jar                   | None                                     |
       | LCH   | tardis                    | 0.1.0D               | tardis-0.1.0D.jar                                 | None                                     |
       | LCH   | regeneration              | 1.6.6                | Regeneration-1.12.2-1.6.6.jar                     | None                                     |
       | LCH   | resourceloader            | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | sgcraft                   | 1.13.2               | SGCraft-2.0.1.jar                                 | None                                     |
       | LCH   | bq_standard               | 3.4.159              | StandardExpansion-3.4.159.jar                     | None                                     |
       | LCH   | storagedrawers            | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
       | LCH   | supersoundmuffler         | 1.0.2.10             | supersoundmuffler-1.12.2-1.0.2.10.jar             | None                                     |
       | LCH   | toastcontrol              | 1.8.1                | Toast Control-1.12.2-1.8.1.jar                    | None                                     |
       | LCH   | tombstone                 | 3.5.5                | tombstone-3.5.5-1.12.jar                          | None                                     |
       | LCH   | torchmaster               | 1.7.1.74             | torchmaster_1.12.2-1.7.1.74.jar                   | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCH   | tropicraft                | 7.1.9.115            | tropicraft-MC1.12.2-7.1.9.115.jar                 | None                                     |
       | LCH   | vanillafix                | 1.0.10-SNAPSHOT      | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCH   | worldstripper             | 1.6.0-1.12.2         | World-Stripper-1.6.0-1.12.2.jar                   | None                                     |
       | LCH   | xtones                    | 1.12-1.0.8-11        | Xtones-1.12-1.0.8-11.jar                          | None                                     |
       | LCH   | zettaindustries           | 1.3                  | zettaindustries-1.3-1.12.2-161.jar                | None                                     |
       | LCH   | phosphor-lighting         | 1.12.2-0.2.4         | phosphor-1.12.2-0.2.4+build46-universal.jar       | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCH   | k9                        | 1.12.2-1.3.1.2       | k9-1.12.2-1.3.1.2.jar                             | None                                     |
       | LCH   | moresoundconfig           | 1.0.4                | moresoundconfig-1.0.4.jar                         | 7904c4e13947c8a616c5f39b26bdeba796500722 |
       | LCH   | reauth                    | 3.6.0                | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCH   | thebetweenlands           | 3.4.9                | TheBetweenlands-3.4.9-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCH   | midnight                  | 0.3.5                | themidnight-0.3.5.jar                             | None                                     |
       | LCH   | weeping-angels            | 1.12.2-37            | weeping-angels-37.jar                             | None                                     |
       | LCH   | eleccoreloader            | 1.9.452              | ElecCore-1.12.2-1.9.452.jar                       | None                                     |
  Loaded coremods (and transformers): SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
                                        pl.asie.splashanimation.core.SplashProgressTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
                                        openeye.asm.MultiTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
                                        
                                      FMLModule (mdxlib-3.0.0.15.jar)
                                        com.asx.mdx.AccessTransformer
                                      midnight (themidnight-0.3.5.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
                                        ichttt.mods.moresoundconfig.asm.MSCTransformer
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar)
                                        
                                      ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
                                        shetiphian.asm.ClassTransformer
                                      Regeneration Sound Handler (Regeneration-1.12.2-1.6.6.jar)
                                        me.swirtzly.regeneration.asm.RegenClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      RandomPatches (randompatches-1.12.2-1.16.3.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      LoadingPlugin (NoNausea-MC1.12-1.0.jar)
                                        lumien.nonausea.asm.ClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 970/PCIe/SSE2'
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  List of loaded APIs: * appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
                       * AtumAPI (0.0.2) from Atum-1.12.2-2.0.10.jar
                       * AVPAPI (1.0.0) from aliensvspredator-6.0.0.34.jar
                       * BetterQuesting|API (3.2) from BetterQuesting-3.5.300.jar
                       * BetterQuesting|API2 (3.1) from BetterQuesting-3.5.300.jar
                       * BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
                       * BetweenlandsAPI (1.12.2) from TheBetweenlands-3.4.9-universal.jar
                       * Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * CSLib|API (1.0.1) from PTRLib-1.0.4.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * Culinary Construct API (1) from culinaryconstruct-1.3.3.jar
                       * ElecCoreAPI (1.0.0) from ElecCore-1.12.2-1.9.452.jar
                       * ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-89.jar
                       * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-89.jar
                       * journeymap|client-api (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.283.jar
                       * MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
                       * PatchouliAPI (6) from Patchouli-1.0-20.jar
                       * railcraft:api_carts (3.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_charge (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_core (3.2.0) from railcraft-12.0.0.jar
                       * railcraft:api_crafting (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_events (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_fuel (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_helpers (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_items (2.4.0) from railcraft-12.0.0.jar
                       * railcraft:api_signals (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_tracks (5.1.1) from railcraft-12.0.0.jar
                       * StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * Thaumcraft|API (6.0.2) from railcraft-12.0.0.jar
                       * theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.28.jar
                       * tombstone-api (1.0.2) from tombstone-3.5.5-1.12.jar
                       * tombstone-api-capability (1.0.2) from tombstone-3.5.5-1.12.jar
                       * tombstone-api-event (1.0.2) from tombstone-3.5.5-1.12.jar
                       * tombstone-api-magic (1.0.2) from tombstone-3.5.5-1.12.jar
                       * tombstone-api-recipe (1.0.2) from tombstone-3.5.5-1.12.jar
  Suspected Mods: Aether II (aether)
  Launched Version: forge-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by ProsperCraft** [comment]
This is not happening to anyone else.

Please follow the steps in this video, reinstall the pack, and report back.

https://youtu.be/-uUr1VAnkcs
